Rework zsh

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -3,6 +3,15 @@
 #
 
 ########
+# init #
+########
+
+# Start dotfiles debug log
+. ${HOME}/.zsh/lib/mlog.sh
+MLOG_ENABLED=${MLOG_ENABLED:-}
+mlog::start
+
+########
 # Base #
 ########
 
@@ -39,13 +48,15 @@ if [[ ${ZIM_HOME}/init.zsh -ot ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
 fi
 source ${ZIM_HOME}/init.zsh
 
+mlog::print "Done Zim init"
+
 #################
 # Zim post-init #
 #################
 
-#################
-# Customization #
-#################
+#####################
+# zsh customization #
+#####################
 
 # MORE history
 HISTFILE=~/.zhistory
@@ -66,22 +77,148 @@ setopt INTERACTIVE_COMMENTS
 # Remove path separator from WORDCHARS.
 #WORDCHARS=${WORDCHARS//[\/]}
 
+###########
+# Exports #
+###########
+
+export BAT_THEME="OneHalfLight" # https://github.com/sharkdp/bat
+export PURE_PROMPT_SYMBOL="λ" # https://github.com/sindresorhus/pure
+export CLOUDSDK_PYTHON=python3
+export KUBECONFIG="$HOME/.kube/config"
+export SOURCES_ROOT="${HOME}/sources"
+export DOTFILES_ROOT="${HOME}/sources/github.com/hypnoglow/dotfiles"
+export EDITOR=vim
+
+. ${HOME}/.zshrc.d/$(uname -s)/__exports.sh
+
+###########
+# Plugins #
+###########
+
+[[ -d ~/.zplug ]] || {
+    git clone https://github.com/zplug/zplug ${ZPLUG_HOME:-"${HOME}/.zplug"}
+}
+
+source ~/.zplug/init.zsh
+
+# Fish shell feature.
+if [ "$TERM" != "linux" ]; then
+    zplug "zsh-users/zsh-autosuggestions"
+fi
+
+. ${HOME}/.zshrc.d/$(uname -s)/__plugins.sh
+
+if ! zplug check --verbose; then
+  printf "Install zsh plugins? [y/N]: "
+  if read -q; then
+    echo; zplug install
+  fi
+fi
+
+zplug load
+
 ############
 # Includes #
 ############
 
-# Include all .sh files from ~/.zshrc.d
-if [ -d ${HOME}/.zshrc.d ]; then
-    for file in ${HOME}/.zshrc.d/*.sh ; do
-        [ -r ${file} ] && . ${file}
-    done
-    unset file
+# Prompt. Note that other plugins that modify prompt must not be included BEFORE
+# this, otherwise they will not take effect.
+if type -f starship &> /dev/null; then
+    eval "$(starship init zsh)"
 fi
 
-# Include local files if any exist.
+[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
+
+# https://github.com/direnv/direnv
+[ -x "$(which direnv 2>/dev/null)" ] && eval "$(direnv hook zsh)"
+
+aws_completion="/usr/local/bin/aws_zsh_completer.sh"
+if [ -e "$aws_completion" ]; then
+    source "$aws_completion"
+fi
+unset aws_completion
+
+gcloud_completion="/opt/google-cloud-sdk/completion.zsh.inc"
+if [ -e "$gcloud_completion" ]; then
+    source "$gcloud_completion"
+fi
+unset gcloud_completion
+
+if type -f kubectl &> /dev/null; then
+    source <(kubectl completion zsh)
+fi
+
+if type -f helm &> /dev/null; then
+    # Temporary fix.
+    # See: https://github.com/helm/helm/issues/5046#issuecomment-463576351
+    #source <(helm completion zsh)
+    source <(helm completion zsh | sed -E 's/\["(.+)"\]/\[\1\]/g')
+fi
+
+if [ -x "$(which minikube 2>/dev/null)" ]; then
+    source <(minikube completion zsh)
+fi
+
+if type -f stern &> /dev/null; then
+    source <(stern --completion=zsh)
+fi
+
+if type -f kitty &> /dev/null; then
+    kitty + complete setup zsh | source /dev/stdin
+fi
+
+if type -f golangci-lint &> /dev/null; then
+    golangci-lint completion zsh | source /dev/stdin
+fi
+
+. ${HOME}/.zshrc.d/$(uname -s)/__includes.sh
+
+# https://github.com/jonmosco/kube-ps1
+# NOTE: kube-ps1 must be included BEFORE this definition.
+kube_ps1_precmd() {
+    PROMPT='$(kube_ps1)'$PROMPT
+}
+if [ "${KUBE_PS1_SHELL}" = "zsh" ]; then
+    KUBE_PS1_SUFFIX=") " # Add space to separate prompt symbol
+    if type -f starship &> /dev/null; then
+        precmd_functions+=(kube_ps1_precmd)
+    else
+        PROMPT='$(kube_ps1)'$PROMPT
+    fi
+fi
+
+###########
+# Aliases #
+###########
+
+. ${HOME}/.zshrc.d/__aliases.sh
+. ${HOME}/.zshrc.d/$(uname -s)/__aliases.sh
+
+###############
+# Keybindings #
+###############
+
+. ${HOME}/.zshrc.d/__keybindings.sh
+. ${HOME}/.zshrc.d/$(uname -s)/__keybindings.sh
+
+#########
+# Local #
+#########
+
 if [ -d ${HOME}/.zshrc.d/local ]; then
+    mlog::print "Load local zsh includes"
     for file in ${HOME}/.zshrc.d/local/*.sh ; do
         [ -r ${file} ] && . ${file}
+        mlog::print "Loaded file ${file}"
     done
     unset file
+    mlog::print "Done loading local zsh includes"
 fi
+
+####################
+# Finish & Cleanup #
+####################
+
+mlog::print "Loaded all"
+mlog::cleanup
+unset MLOG_ENABLED
